### ISSUE TITLE
Privately share?

### ISSUE THREAD

**Issue by ShawonAshraf** [pathao-eng/challenges-2019#2]
Can you please elaborate on this term? Because forked repositories can't be made private. Do you want participants to push their code in their own forks and then send you the link via email? Their work would still be public on GitHub and "share privately" would seem confusing.

**Comment by bkraad47** [comment]
Both, private repositories are now free.
https://thenextweb.com/dd/2019/01/05/github-now-gives-free-users-unlimited-private-repositories/

**Comment by jabertuhin** [comment]
@bkraad47 Yes, it's free. But after forking a public repository, I can not make it private. If I want to to make it private then I have to make a duplicate copy of that.
It will be really helpful if you can make the sharing description more clear to understand
![public_private](https://user-images.githubusercontent.com/22750032/52257626-b81e8180-2945-11e9-8926-69508aff0550.png)
.

**Comment by bkraad47** [comment]
[jabertuhin](/jabertuhin) You can make a duplicate copy and start your project that's fine. As long as there are clear commits.

**Comment by ShawonAshraf** [comment]
Okay then, who should we give read access to the private repo then? @bkraad47 Just sending the link to a private repo won't work.

**Comment by bkraad47** [comment]
@ShawonAshraf  yes

**Comment by ShawonAshraf** [comment]
@bkraad47 I think you didn't get my question. Let me repeat. Who should I give read access to my repo? Any email address or a person with a GitHub account? Like Bitbucket lets you add observers? You need to clearly specify that. Or finding out the corresponding person or authority is part of the challenge too? (It's mind boggling that pathao can launch a challenge but the engineering team doesn't care to write a clear readme. :ok_hand: )

**Comment by bkraad47** [comment]
Hey @ShawonAshraf good catch. One of the things we value here at Pathao is the ability to work together intuitively across teams on problems. As per your comments, we have updated the readme to reflect better instructions.

Essentially, we'd like to see code submission's both from github and email. As mentioned we would like to see your git commits. So please provide us access to your repo by adding us as collaborators. Information on that has been added to our Readme.md file.

<img width="1011" alt="screen shot 2019-02-09 at 5 52 01 pm" src="https://user-images.githubusercontent.com/11604688/52520628-ab779180-2c95-11e9-9900-9b6f8b9f626e.png">

**Comment by ShawonAshraf** [comment]
Thanks for clearing that up!
